hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("clipse -listen")
    --hl.exec_cmd("wl-clip-persist --clipboard regular")
    --hl.exec_cmd("wl-clip-persist --clipboard regular --write-timeout 1000 --ignore-event-on-error")
    --hl.exec_cmd("wl-paste --type text --watch cliphist store")
    --hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("udiskie")
end)
