#!/bin/sh

filename=$(date +%F_%T.mp4)

if [ -z $(pgrep wf-recorder) ] ; then
    if [ -z $(pgrep slurp) ]; then
    	notify-send "Recording Started"
        wf-recorder -f $HOME/Videos/$filename -g "$(slurp)" >/dev/null 2>&1 &
    	sleep 2
    	while [ ! -z $(pgrep -x slurp) ]; do wait; done
    	pkill -RTMIN+8 waybar
    else
    	killall -s SIGINT slurp
    fi
else
	killall -s SIGINT wf-recorder
	notify-send "Recording Complete" "(Videos/$filename)"
	# action=$(notify-send --action=open='Show' "Recording Complete" "(Videos/$filename)")
	while [ ! -z $(pgrep -x wf-recorder) ]; do wait; done
	pkill -RTMIN+8 waybar
    # if [[ $action == "open" ]]; then
    #     xdg-open ~/Videos
    #     pkill -RTMIN+8 waybar
    # fi
fi
